# Cauchy Stress Tensor
# Principal Stresses & Stress Invariants
This is a summary of all the available expressions.  
More details can be found at:  
https://en.wikipedia.org/wiki/Cauchy_stress_tensor

In [1]:
import numpy as np

## Stress Definition

### Vector Form
$$
\sigma_{ij} = \left[ \begin{array}{c}
    \sigma_{xx} \\
    \sigma_{yy} \\
    \sigma_{zz} \\
    \sigma_{yz} \\
    \sigma_{xz} \\
    \sigma_{xy} \\
    \end{array} \right]
$$

In [2]:
s_vec = np.array([10,20,30,5,10,15])

print(s_vec)

[10 20 30  5 10 15]


### Matrix Form
$$
\sigma_{ij} = \left[ \begin{array}{ccc}
    \sigma_{xx} && \sigma_{xy} && \sigma_{xz} \\
    \sigma_{yx} && \sigma_{yy} && \sigma_{yz} \\
    \sigma_{zx} && \sigma_{zy} && \sigma_{zz} \\
    \end{array} \right]
$$

In [3]:
s = np.array([
    [s_vec[0],s_vec[5],s_vec[4]],
    [s_vec[5],s_vec[1],s_vec[3]],
    [s_vec[4],s_vec[3],s_vec[2]]
])

print(s)

[[10 15 10]
 [15 20  5]
 [10  5 30]]


Also define Kronecker's Delta

In [4]:
d = np.eye(3)

print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Stress Invariants

### First Invariant
$$
I_1 = \sigma_{xx}+\sigma_{yy}+\sigma_{zz}
$$
$$
I_1 = \sigma_{kk}
$$
$$
I_1 = tr(\sigma)
$$

In [5]:
I1 = s[0,0]+s[1,1]+s[2,2]

I1_alt1 = 0;
for k in [0,1,2]:
    I1_alt1 = I1_alt1 + s[k,k]

I1_alt2 = np.trace(s)

print(I1)
print(I1_alt1)
print(I1_alt2)

60
60
60


### Second Invariant
$$
I_2 = \left| \begin{array}{cc} \sigma_{yy} && \sigma_{yz} \\ \sigma_{zy} && \sigma_{zz} \end{array} \right| +
      \left| \begin{array}{cc} \sigma_{xx} && \sigma_{xz} \\ \sigma_{zx} && \sigma_{zz} \end{array} \right| +
      \left| \begin{array}{cc} \sigma_{xx} && \sigma_{xy} \\ \sigma_{yx} && \sigma_{yy} \end{array} \right|
$$
$$
I_2 = \sigma_{xx} \sigma_{yy} + \sigma_{yy} \sigma_{zz} + \sigma_{xx} \sigma_{zz} - \sigma_{xy}^2 - \sigma_{xz}^2 - \sigma_{yz}^2
$$
$$
I_2 = \frac{1}{2} \left( \sigma_{ii} \sigma_{jj} - \sigma_{ij} \sigma_{ji} \right)
$$
$$
I_2 = \frac{1}{2} \left[ \left( tr(\sigma) \right)^2 - tr(\sigma^2) \right]
$$

In [6]:
I2 = np.linalg.det(np.array([[s[1,1],s[1,2]],[s[2,1],s[2,2]]])) + \
    np.linalg.det(np.array([[s[0,0],s[0,2]],[s[2,0],s[2,2]]])) + \
    np.linalg.det(np.array([[s[0,0],s[0,1]],[s[1,0],s[1,1]]]))

I2_alt1 = s[0,0]*s[1,1]+s[1,1]*s[2,2]+s[0,0]*s[2,2]-s[0,1]**2-s[0,2]**2-s[1,2]**2

I2_alt2 = 0
for i in [0,1,2]:
    for j in [0,1,2]:
        I2_alt2 = I2_alt2 + (1/2)*(s[i,i]*s[j,j]-s[i,j]*s[j,i])

I2_alt3 = (1/2)*(np.trace(s)**2-np.trace(s@s))

print(I2)
print(I2_alt1)
print(I2_alt2)
print(I2_alt3)

750.0000000000002
750
750.0
750.0


### Third Invariant
$$
I_3 = \left| \begin{array}{ccc}
    \sigma_{xx} && \sigma_{xy} && \sigma_{xz} \\
    \sigma_{yx} && \sigma_{yy} && \sigma_{yz} \\
    \sigma_{zx} && \sigma_{zy} && \sigma_{zz} \\
    \end{array} \right|
$$
$$
I_3 = \sigma_{xx}\sigma_{yy}\sigma_{zz} + 2\sigma_{xy}\sigma_{xz}\sigma_{yz} - \sigma_{xx}\sigma_{yz}^2 - \sigma_{yy}\sigma_{xz}^2 - \sigma_{zz}\sigma_{xy}^2
$$

In [7]:
I3 = np.linalg.det(s)

I3_alt1 = s[0,0]*s[1,1]*s[2,2]+2*s[0,1]*s[0,2]*s[1,2]-s[0,0]*s[1,2]**2-s[1,1]*s[0,2]**2-s[2,2]*s[0,1]**2

print(I3)
print(I3_alt1)

-1500.0
-1500


## Principal Stresses

### Characteristic Polynomial
$$
\left| \sigma_{ij} - \lambda\delta_{ij} \right| = -\lambda^3 + I_1\lambda^2 - I_2\lambda + I_3 = 0
$$

In [8]:
poly = np.array([-1,+I1,-I2,+I3])
s_prin = np.roots(poly)

print(s_prin)

[40.63415448 21.11418479 -1.74833927]


### Additional Expressions
$$
I_1 = \sigma_1 + \sigma_2 + \sigma_3
$$
$$
I_2 = \sigma_1 \sigma_2 + \sigma_2 \sigma_3 + \sigma_3 \sigma_1
$$
$$
I_3 = \sigma_1 \sigma_2 \sigma_3
$$

In [9]:
I1_prin = s_prin[0]+s_prin[1]+s_prin[2]
I2_prin = s_prin[0]*s_prin[1]+s_prin[1]*s_prin[2]+s_prin[2]*s_prin[0]
I3_prin = s_prin[0]*s_prin[1]*s_prin[2]

print(I1,I1_prin)
print(I2,I2_prin)
print(I3,I3_prin)

60 59.99999999999997
750.0000000000002 749.9999999999994
-1500.0 -1499.9999999999986


## Deviatoric Stresses

### Mean Stress & Deviatoric Stress Tensor
$$
p = \frac{1}{3}I_1
$$
$$
s = \sigma_{ij} - p\delta_{ij}
$$

In [10]:
p = I1/3
sp = p*d
sq = s-sp

print(p)
print(sq)

20.0
[[-10.  15.  10.]
 [ 15.   0.   5.]
 [ 10.   5.  10.]]


## Deviatoric Stress Invariants

### First Invariant
$$
J_1 = 0
$$

In [11]:
J1 = 0
print(J1)

0


### Second Invariant
$$
J_2 = \frac{1}{2} s_{ij}s_{ij}
$$
$$
J_2 = \frac{1}{2} (s_{xx}^2 + s_{yy}^2 + s_{zz}^2 + 2s_{xy}^2 + 2s_{xz}^2 + 2s_{yz}^2)
$$
$$
J_2 = \frac{1}{2} tr(s^2)
$$
$$
J_2 = \frac{1}{6} \left[ (\sigma_{xx}-\sigma_{yy})^2+(\sigma_{yy}-\sigma_{zz})^2+(\sigma_{zz}-\sigma_{xx})^2 \right]
    +\sigma_{xy}^2+\sigma_{yz}^2+\sigma_{zx}^2
$$
$$
J_2 = \frac{1}{6} \left[ (\sigma_{1}-\sigma_{2})^2+(\sigma_{2}-\sigma_{3})^2+(\sigma_{3}-\sigma_{1})^2 \right]
$$
$$
J_2 = \frac{1}{3} I_1^2 - I_2
$$
$$
J_2 = \frac{1}{2} \left[ tr(\sigma^2)-\frac{1}{3}tr(\sigma)^2 \right]
$$

In [12]:
J2=0
for i in [0,1,2]:
    for j in [0,1,2]:
        J2 = J2 + (1/2)*sq[i,j]*sq[j,i]

J2_alt1 = (1/2)*(sq[0,0]**2+sq[1,1]**2+sq[2,2]**2+2*sq[0,1]**2+2*sq[0,2]**2+2*sq[1,2]**2)

J2_alt2 = (1/2)*np.trace(sq@sq)

J2_alt3 = (1/6)*((s[0,0]-s[1,1])**2+(s[1,1]-s[2,2])**2+(s[2,2]-s[0,0])**2)+s[0,1]**2+s[1,2]**2+s[2,0]**2

J2_alt4 = (1/6)*((s_prin[0]-s_prin[1])**2+(s_prin[1]-s_prin[2])**2+(s_prin[2]-s_prin[0])**2)

J2_alt5 = (1/3)*I1**2-I2

J2_alt6 = (1/2)*(np.trace(s@s)-(1/3)*np.trace(s)**2)

print(J2)
print(J2_alt1)
print(J2_alt2)
print(J2_alt3)
print(J2_alt4)
print(J2_alt5)
print(J2_alt6)

450.0
450.0
450.0
450.0
449.9999999999993
449.9999999999998
450.0


### Third Invariant
$$
J_3 = \left| \begin{array}{ccc}
    s_{xx} && s_{xy} && s_{xz} \\
    s_{yx} && s_{yy} && s_{yz} \\
    s_{zx} && s_{zy} && s_{zz} \\
    \end{array} \right|
$$
$$
J_3 = \frac{1}{3} s_{ij}s_{jk}s_{ki}
$$
$$
J_3 = \frac{1}{3} (s_{xx}^3+s_{yy}^3+s_{zz}^3 + 6s_{xy}s_{xz}s_{yz} + 3s_{xx}s_{xy}^2+3s_{xx}s_{xz}^2 + 3s_{yy}s_{yx}^2+3s_{yy}s_{yz}^2 + 3s_{zz}s_{zx}^2+3s_{zz}s_{zy}^2)
$$
$$
J_3 = s_{xx}s_{yy}s_{zz}+2s_{xy}s_{xz}s_{yz}-s_{xx}s_{yz}^2-s_{yy}s_{xz}^2-s_{zz}s_{xy}^2
$$
$$
J_3 = \frac{1}{3} tr(s^3)
$$
$$
J_3 = \frac{2}{27} I_1^3 - \frac{1}{3}I_1I_2 + I_3
$$
$$
J_3 = \frac{1}{3} \left[ tr(\sigma^3) - tr(\sigma^2)tr(\sigma) + \frac{2}{9}tr(\sigma)^3 \right]
$$

In [13]:
J3 = np.linalg.det(sq)

J3_alt1=0
for i in [0,1,2]:
    for j in [0,1,2]:
        for k in [0,1,2]:
            J3_alt1 = J3_alt1 + (1/3)*sq[i,j]*sq[j,k]*sq[k,i]

J3_alt2 = (1/3)*(sq[0,0]**3+sq[1,1]**3+sq[2,2]**3+ \
    6*sq[0,1]*sq[0,2]*sq[1,2]+ \
    3*sq[0,0]*sq[0,1]**2+3*sq[0,0]*sq[0,2]**2+ \
    3*sq[1,1]*sq[1,0]**2+3*sq[1,1]*sq[1,2]**2+ \
    3*sq[2,2]*sq[2,0]**2+3*sq[2,2]*sq[2,1]**2)

J3_alt3 = sq[0,0]*sq[1,1]*sq[2,2]+2*sq[0,1]*sq[0,2]*sq[1,2] \
    -sq[0,0]*sq[1,2]**2-sq[1,1]*sq[0,2]**2-sq[2,2]*sq[0,1]**2

J3_alt4 = (1/3)*np.trace(sq@sq@sq)

J3_alt5 = (2/27)*I1**3-(1/3)*I1*I2+I3

J3_alt6 = (1/3)*(np.trace(s@s@s)-np.trace(s@s)*np.trace(s)+(2/9)*np.trace(s)**3)

print(J3)
print(J3_alt1)
print(J3_alt2)
print(J3_alt3)
print(J3_alt4)
print(J3_alt5)
print(J3_alt6)

-500.0000000000003
-499.9999999999998
-500.0
-500.0
-500.0
-500.00000000000364
-500.0


## Principal Deviatoric Stresses

### Characteristic Polynomial
$$
\left| s_{ij} - \lambda\delta_{ij} \right| = \lambda^3 - J_1\lambda^2 - J_2\lambda - J_3 = 0
$$

In [14]:
poly_q = np.array([1,-J1,-J2,-J3])
sq_prin = np.roots(poly_q)

print(sq_prin)

[-21.74833927  20.63415448   1.11418479]


### Additional Expressions
$$
J_1 = 0
$$
$$
J_2 = \frac{1}{2} (s_1^2 + s_2^2 + s_3^2)
$$
$$
J_3 = \frac{1}{3} (s_1^3 + s_2^3 + s_3^3)
$$

In [15]:
J1_prin = 0
J2_prin = (1/2)*(sq_prin[0]**2+sq_prin[1]**2+sq_prin[2]**2)
J3_prin = (1/3)*(sq_prin[0]**3+sq_prin[1]**3+sq_prin[2]**3)

print(J1,J1_prin)
print(J2,J2_prin)
print(J3,J3_prin)

0 0
450.0 450.00000000000017
-500.0000000000003 -500.0000000000087


## Other Stress Components

### Von Mises Stress
$$
q = \sqrt{3J_2}
$$
Different expressions can be found, based on the expression of $ J_2 $ (see above).

In [16]:
q = np.sqrt(3*J2)

print(q)

36.742346141747674


### Lode Angle
$$
\alpha_s = \frac{1}{3} \arccos \left( \frac{3\sqrt{3}J_3}{2J_2^\frac{3}{2}} \right)
$$

In [17]:
a_s = (np.arccos((3*np.sqrt(3)*J3)/(2*J2**(3/2))))/3

print(a_s)

0.5691008793190673


$$
\beta = \frac{\sin(\alpha_s)}{\sin(\frac{\pi}{3}+\alpha_s)}
$$
$$
\beta = \frac{\sigma_2-\sigma_3}{\sigma_1-\sigma_3}
$$

In [18]:
b_as=np.sin(a_s)/np.sin(np.pi/3+a_s)
b_s=(s_prin[1]-s_prin[2])/(s_prin[0]-s_prin[2])

print(b_as)
print(b_s)

0.5394331962128812
0.5394331962128817


## Alternative Expressions for Principal Stresses
$$
T = \sqrt{J2}
$$
$$
s_1 = \frac{2}{\sqrt3} T \cos\left(\alpha_s\right)
$$
$$
s_2 = -\frac{2}{\sqrt3} T \cos\left(\frac{\pi}{3}+\alpha_s\right)
$$
$$
s_3 = -\frac{2}{\sqrt3} T \cos\left(\frac{\pi}{3}+\alpha_s\right)
$$

In [19]:
T = np.sqrt(J2)
sq_prin_alt = np.array([
    (2/np.sqrt(3))*T*np.cos(a_s),
    -(2/np.sqrt(3))*T*np.cos(np.pi/3+a_s),
    -(2/np.sqrt(3))*T*np.cos(np.pi/3-a_s)
])

print(sq_prin)
print(sq_prin_alt)

[-21.74833927  20.63415448   1.11418479]
[ 20.63415448   1.11418479 -21.74833927]
